apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: notes-build-task
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
    - name: notes-git
      type: git
    params:
    - name: daemon
      default: "tcp://buildkitd:1234"
    - name: dockerfile
      default: Dockerfile
    - name: buildcontext
      default: /workspace/notes-git
    - name: targetstage
      default: target
    - name: push
      default: "true"
  outputs:
    resources:
    - name: notes-image
      type: image
  steps:
  - name: build-test-push
    image: moby/buildkit:latest
    command: [ "buildctl", "--addr=${inputs.params.daemon}", "build",
               "--progress=plain",
               "--frontend=dockerfile.v0",
               "--opt", "filename=${inputs.params.dockerfile}",
               "--local", "context=${inputs.params.buildcontext}",
               "--local", "dockerfile=${inputs.params.buildcontext}",
               "--output", "type=image,name=docker.io/fabijanbajo/notes,push=${inputs.params.push}" ]
