apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: notes-build-task
spec:
  inputs:
    resources:
    - name: notes-git
      type: git
    params:
    - name: daemon
      default: "tcp://buildkitd:1234"
    - name: dockerfile
      default: Dockerfile
    - name: buildcontext
      default: /workspace/notes-git
    - name: targetstage
      default: target
  outputs:
    resources:
    - name: notes-image
      type: image
  steps:
  - name: build-test-push
    image: gcr.io/kaniko-project/executor
    command: ["buildctl", "--addr=${daemon}", "build",
              "--progress=plain",
              "--frontend=dockerfile.v0",
              "--opt", "filename=${inputs.params.dockerfile}",
              "--local", "context=.", "--local", "dockerfile=.",
              "--output", "type=image,name=${outputs.params.notes-image},push=false"]
