stages:
- build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

variables:
  CHART_NAME: notes
  CHART_PATH: ./ops
  DOCKER_REGISTRY: $DOCKERHUB_USER/$PROJECT_NAME
  K8S_URL: https://azure-free-azure-free-a224ad-ab0792b4.hcp.westeurope.azmk8s.io
  K8S_USER_TOKEN: $K8S_USER_TOKEN_SECRET
  HELM_VERSION: "2.12.1"

build_test_push:
  stage: build
  image: docker:stable
  services:
  - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
    REGISTRY_USER: $DOCKERHUB_USER
    REGISTRY_PASSWORD: $DOCKERHUB_PASSWORD
    REGISTRY_DOMAIN: docker.io
    TAG: $CI_COMMIT_SHORT_SHA
  script:
  - ./ops/scripts/build_test_push.sh
