replicaCount: 1
image:
  repository: fabijanbajo/notes
  tag: dev
  pullPolicy: Always
service:
  type: NodePort
  port: 80
  nodePort: 30001
ingress:
  enabled: false
  annotations: {}
  hosts:
  - host: notes.bajo-k8s.online
    paths:
    - /
  tls: []
resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
app:
  nodeEnv: development
  loggerLevel: info
  mongodbServiceName: mongodb
  mongodbPort: "27017"
  mongodbUsername: test
  mongodbPassword: test

mongodb:
  enabled: true
  image:
    tag: 4.0.9
  usePassword: true
  mongodbUsername: test
  mongodbPassword: test
  mongodbDatabase: notes
  service:
    annotations: {}
    type: ClusterIP
    port: 27017
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  updateStrategy:
    type: RollingUpdate
  persistence:
    enabled: false
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  metrics:
    enabled: false